inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "vendor/bundle/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/services/**/*" # Inheriting BaseService without calling super is OK.

Metrics/BlockLength:
  Exclude:
    - "Guardfile"
    - "scripts/*"
    - "spec/**/*"
    - "config/initializers/*"
    - "config/environments/*"
    - "config/routes.rb"

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 20

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/ContextWording:
  Enabled: False

RSpec/ExampleLength:
  Max: 30
  Exclude:
    - "spec/features/**/*"
    - "spec/requests/api/**/*"

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/MessageChain:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - "spec/features/**/*"
