upsert_stats_job:
  cron: "0 22 * * *" # we compute stats once a day, at 22:00
  class: "UpsertStatsJob"
send_invitation_reminders_job:
  cron: "0 11 * * *" # we compute stats once a day, at 11:00
  class: "SendInvitationRemindersJob"
