test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

scaleway:
  service: S3
  access_key_id: <%= ENV['SCALEWAY_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['SCALEWAY_SECRET_ACCESS_KEY'] %>
  # No need to set a region, it's automatically inferred from the endpoint
  # see: https://edgeguides.rubyonrails.org/active_storage_overview.html#s3-service-amazon-s3-and-s3-compatible-apis
  endpoint: https://rdv-insertion-medias-<%= ENV["SENTRY_ENVIRONMENT"] %>.s3.fr-par.scw.cloud
  bucket: rdv-insertion-medias-<%= ENV["SENTRY_ENVIRONMENT"] %>
