rsa_orientation:
  rdv_title: rendez-vous d'orientation
  rdv_title_by_phone: rendez-vous d'orientation téléphonique
  display_mandatory_warning: true
  display_punishable_warning: false
rsa_accompagnement: &rsa_accompagnement_values
  rdv_title: rendez-vous d'accompagnement
  rdv_title_by_phone: rendez-vous d'accompagnement téléphonique
  display_mandatory_warning: true
  display_punishable_warning: true
rsa_accompagnement_social: *rsa_accompagnement_values # we reuse the rsa_accompagnement_values
rsa_accompagnement_sociopro: *rsa_accompagnement_values # we reuse the rsa_accompagnement_values
rsa_follow_up:
  rdv_title: rendez-vous de suivi avec votre référent de parcours
  rdv_title_by_phone: rendez-vous de suivi téléphonique avec votre référent de parcours
  display_mandatory_warning: false
  display_punishable_warning: false
rsa_cer_signature:
  rdv_title: rendez-vous pour construire et signer votre Contrat d'Engagement Réciproque
  rdv_title_by_phone: rendez-vous téléphonique pour construire et signer votre Contrat d'Engagement Réciproque
  display_mandatory_warning: true
  display_punishable_warning: false
