categories:
  ### Il faut avoir en tête la phrase suivante: "Vous êtes invité/convoqué à un rdv_title afin rdv_purpose"
  rsa_orientation:
    rdv_title: rendez-vous d'orientation
    rdv_title_by_phone: rendez-vous d'orientation téléphonique
    rdv_purpose: de démarrer un parcours d'accompagnement
    applicant_designation: bénéficiaire du RSA
    display_mandatory_warning: true
    display_punishable_warning: false
  rsa_accompagnement: &rsa_accompagnement_values
    rdv_title: rendez-vous d'accompagnement
    rdv_title_by_phone: rendez-vous d'accompagnement téléphonique
    rdv_purpose: de démarrer un parcours d'accompagnement
    applicant_designation: bénéficiaire du RSA
    display_mandatory_warning: true
    display_punishable_warning: true
  rsa_accompagnement_social: *rsa_accompagnement_values # we reuse the rsa_accompagnement_values
  rsa_accompagnement_sociopro: *rsa_accompagnement_values # we reuse the rsa_accompagnement_values
  rsa_follow_up:
    rdv_title: rendez-vous de suivi
    rdv_title_by_phone: rendez-vous de suivi téléphonique
    rdv_purpose: de faire un point avec votre référent de parcours
    applicant_designation: bénéficiaire du RSA
    display_mandatory_warning: false
    display_punishable_warning: false
  rsa_cer_signature:
    rdv_title: rendez-vous de signature de CER
    rdv_title_by_phone: rendez-vous téléphonique de signature de CER
    rdv_purpose: de construire et signer votre Contrat d'Engagement Réciproque
    applicant_designation: bénéficiaire du RSA
    display_mandatory_warning: true
    display_punishable_warning: false
  rsa_main_tendue:
    rdv_title: entretien de main tendue
    rdv_title_by_phone: entretien téléphonique de main tendue
    rdv_purpose: de faire le point sur votre situation
    applicant_designation: bénéficiaire du RSA
    display_mandatory_warning: true
    display_punishable_warning: false
  rsa_atelier_collectif_mandatory:
    rdv_title: atelier collectif
    rdv_title_by_phone: atelier collectif
    rdv_purpose: de vous aider dans votre parcours d'insertion
    applicant_designation: bénéficiaire du RSA
    display_mandatory_warning: true
    display_punishable_warning: false
  rsa_spie:
    rdv_title: rendez-vous d'accompagnement
    rdv_title_by_phone: rendez-vous d'accompagnement téléphonique
    rdv_purpose: de démarrer un parcours d'accompagnement
    applicant_designation: demandeur d'emploi
    display_mandatory_warning: true
    display_punishable_warning: true
  rsa_integration_information:
    rdv_title: rendez-vous d'intégration
    rdv_title_by_phone: rendez-vous d'intégration téléphonique
    applicant_designation: bénéficiaire du RSA
    rdv_purpose: d'être informé de vos droits et de vos devoirs
    display_mandatory_warning: true
    display_punishable_warning: false
